### PR TITLE
Plonk verifier E2E example

### PR DESCRIPTION
**Pull request by ajuggler**
Plonk verifier E2E example now runs correctly on both SanchoNet and local testnet.  Updated documentation on `./e2e-test/README.md`.

### CODE REVIEW

**Comment by ajuggler** [comment]
Note that now `forwardingMint` validator is parameterized with integers.  Motivation for this is that its address was getting very crowded with UTxOs.  Giving a different integer parameter now results in a different address.

**Comment by vlasin** [comment]
Looking great, Antonio! One suggestion: how difficult will it be to merge `local-testnet` folder with the `e2e-test` folder? Specifically, we currently have almost the same script files for posting transactions in the ZK-KYC example for sancho.net and for the local testnet. I think it would be easier to maintain.

**Comment by zlonast** [comment]
This looks great to me too. I think we should switch from JSON to CBOR entirely.

**Comment by ajuggler** [comment]
> Looking great, Antonio! One suggestion: how difficult will it be to merge `local-testnet` folder with the `e2e-test` folder? Specifically, we currently have almost the same script files for posting transactions in the ZK-KYC example for sancho.net and for the local testnet. I think it would be easier to maintain.

Yes, I think it is desirable and easy to implement.  Main difference in transaction scripts is the pause time after submitting a transaction.  By passing optional parameter to shell scripts user can control the pause time, and default (longer) time will be used if no parameter is passed.  Will do.

**Comment by ajuggler** [comment]
Moved local-testnet to e2e-test.  Now plonk-example transactions are executed by the same scripts for both SanchoNet and local-testnet.  (Only initialization scripts are different.)  Updated e2e-test/README .

**Comment by ajuggler** [comment]
> This looks great to me too. I think we should switch from JSON to CBOR entirely.

Done.

**Review by zlonast — APPROVED** [review]

**Review by vlasin — APPROVED** [review]

**Pull request merged**
